title: Alex Prakash
email: your-email@example.com
description: >-
  Personal blog about building, thinking, and shipping.
author: Alex Prakash
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: Alex-Prakash

# Build settings
markdown: kramdown
theme: minima # We will override this by providing our own layouts, but this is a safe default for GHP
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be defined by an exact filename, a pattern, or a file extension.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
